//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace DoenaSoft.DVDProfiler.DVDProfilerXML.Version395
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Collection
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DVD")]
        public DVD[] DVDList;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DVD
    {

        /// <remarks/>
        public System.DateTime ProfileTimestamp;

        /// <remarks/>
        public string ID;

        /// <remarks/>
        public string ID_Base;

        /// <remarks/>
        public int ID_VariantNum;

        /// <remarks/>
        public int ID_LocalityID;

        /// <remarks/>
        public string ID_LocalityDesc;

        /// <remarks/>
        public DVDID_Type ID_Type;

        /// <remarks/>
        public MediaTypes MediaTypes;

        /// <remarks/>
        public string UPC;

        /// <remarks/>
        public string CollectionNumber;

        /// <remarks/>
        public CollectionType CollectionType;

        /// <remarks/>
        public string Title;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DistTrait")]
        public string Edition;

        /// <remarks/>
        public string OriginalTitle;

        /// <remarks/>
        public string CountryOfOrigin;

        /// <remarks/>
        public string CountryOfOrigin2;

        /// <remarks/>
        public string CountryOfOrigin3;

        /// <remarks/>
        public int ProductionYear;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Released;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleasedSpecified;

        /// <remarks/>
        public int RunningTime;

        /// <remarks/>
        public string RatingSystem;

        /// <remarks/>
        public string Rating;

        /// <remarks/>
        public int RatingAge;

        /// <remarks/>
        public int RatingVariant;

        /// <remarks/>
        public string RatingDetails;

        /// <remarks/>
        public string CaseType;

        /// <remarks/>
        public bool CaseSlipCover;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CaseSlipCoverSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Genre", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Genres")]
        public string[] GenreList;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Region", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Regions")]
        public string[] RegionList;

        /// <remarks/>
        public Format Format;

        /// <remarks/>
        public Features Features;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Studio", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Studios")]
        public string[] StudioList;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MediaCompany", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("MediaCompanies")]
        public string[] MediaCompanyList;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AudioTrack", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Audio")]
        public AudioTrack[] AudioList;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Subtitle", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Subtitles")]
        public string[] SubtitleList;

        /// <remarks/>
        public Price SRP;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Actor", typeof(CastMember), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(Divider), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Actors")]
        public object[] CastList;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Credit", typeof(CrewMember), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(CrewDivider), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Credits")]
        public object[] CrewList;

        /// <remarks/>
        public string Overview;

        /// <remarks/>
        public string EasterEggs;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Disc", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Discs")]
        public Disc[] DiscList;

        /// <remarks/>
        public string SortTitle;

        /// <remarks/>
        public System.DateTime LastEdited;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastEditedSpecified;

        /// <remarks/>
        public int WishPriority;

        /// <remarks/>
        public int CountAs;

        /// <remarks/>
        public PurchaseInfo PurchaseInfo;

        /// <remarks/>
        public Review Review;

        /// <remarks/>
        public MediaBanners MediaBanners;

        /// <remarks/>
        public Exclusions Exclusions;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Event", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Events")]
        public Event[] EventList;

        /// <remarks/>
        public BoxSet BoxSet;

        /// <remarks/>
        public LoanInfo LoanInfo;

        /// <remarks/>
        public MyLinks MyLinks;

        /// <remarks/>
        public string Notes;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Tags")]
        public Tag[] TagList;

        /// <remarks/>
        public Locks Locks;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public PluginData[] PluginCustomData;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum DVDID_Type
    {

        /// <remarks/>
        UPCEAN,

        /// <remarks/>
        ManualID,

        /// <remarks/>
        DiscID,

        /// <remarks/>
        PluginSpecificID,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MediaTypes
    {

        /// <remarks/>
        public bool DVD;

        /// <remarks/>
        public bool HDDVD;

        /// <remarks/>
        public bool BluRay;

        /// <remarks/>
        public bool UltraHD;

        /// <remarks/>
        public string CustomMediaType;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PluginData
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClassID;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Locks
    {

        /// <remarks/>
        public bool Entire;

        /// <remarks/>
        public bool Covers;

        /// <remarks/>
        public bool Title;

        /// <remarks/>
        public bool MediaType;

        /// <remarks/>
        public bool Overview;

        /// <remarks/>
        public bool Regions;

        /// <remarks/>
        public bool Genres;

        /// <remarks/>
        public bool SRP;

        /// <remarks/>
        public bool Studios;

        /// <remarks/>
        public bool DiscInformation;

        /// <remarks/>
        public bool Cast;

        /// <remarks/>
        public bool Crew;

        /// <remarks/>
        public bool Features;

        /// <remarks/>
        public bool AudioTracks;

        /// <remarks/>
        public bool Subtitles;

        /// <remarks/>
        public bool EasterEggs;

        /// <remarks/>
        public bool RunningTime;

        /// <remarks/>
        public bool ReleaseDate;

        /// <remarks/>
        public bool ProductionYear;

        /// <remarks/>
        public bool CaseType;

        /// <remarks/>
        public bool VideoFormats;

        /// <remarks/>
        public bool Rating;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Tag
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserLink
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CategoryRestriction Category;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum CategoryRestriction
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Empty,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Official Websites")]
        OfficialWebsites,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Fan Sites")]
        FanSites,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Trailers and Clips")]
        TrailersAndClips,

        /// <remarks/>
        Reviews,

        /// <remarks/>
        Ratings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Information")]
        GeneralInformation,

        /// <remarks/>
        Games,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MyLinks
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UserLink", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("CustomLinks")]
        public UserLink[] UserLinkList;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanInfo
    {

        /// <remarks/>
        public bool Loaned;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Due;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DueSpecified;

        /// <remarks/>
        public User User;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User : BasicUser
    {
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmailAddress;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PhoneNumber;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BasicUser
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoxSet
    {

        /// <remarks/>
        public string Parent;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Content", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Contents")]
        public string[] ContentList;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Event
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EventType")]
        public EventType Type;

        /// <remarks/>
        public System.DateTime Timestamp;

        /// <remarks/>
        public string Note;

        /// <remarks/>
        public User User;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum EventType
    {

        /// <remarks/>
        Watched,

        /// <remarks/>
        Returned,

        /// <remarks/>
        Borrowed,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Exclusions
    {

        /// <remarks/>
        public bool MoviePick;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MoviePickSpecified;

        /// <remarks/>
        public bool Mobile;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MobileSpecified;

        /// <remarks/>
        public bool iPhone;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iPhoneSpecified;

        /// <remarks/>
        public bool RemoteConnections;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemoteConnectionsSpecified;

        /// <remarks/>
        public bool DPOPublic;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DPOPublicSpecified;

        /// <remarks/>
        public bool DPOPrivate;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DPOPrivateSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MediaBanners
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MediaBannersRestriction Front;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MediaBannersRestriction Back;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum MediaBannersRestriction
    {

        /// <remarks/>
        On,

        /// <remarks/>
        Off,

        /// <remarks/>
        Automatic,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Review
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Film;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Video;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Audio;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Extras;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PurchaseInfo
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchasePrice")]
        public Price Price;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchasePlace")]
        public string Place;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchasePlaceType")]
        public string Type;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchasePlaceWebsite")]
        public string Website;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseDate", DataType = "date")]
        public System.DateTime Date;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified;

        /// <remarks/>
        public bool ReceivedAsGift;

        /// <remarks/>
        public User GiftFrom;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Price
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DenominationType;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DenominationDesc;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FormattedValue;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Disc
    {

        /// <remarks/>
        public string DescriptionSideA;

        /// <remarks/>
        public string DescriptionSideB;

        /// <remarks/>
        public string DiscIDSideA;

        /// <remarks/>
        public string DiscIDSideB;

        /// <remarks/>
        public string LabelSideA;

        /// <remarks/>
        public string LabelSideB;

        /// <remarks/>
        public bool DualLayeredSideA;

        /// <remarks/>
        public bool DualLayeredSideB;

        /// <remarks/>
        public bool DualSided;

        /// <remarks/>
        public string Location;

        /// <remarks/>
        public string Slot;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrewMember
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MiddleName { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BirthYear { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditType;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditSubtype;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditedAs { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomRole;
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomRoleSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CastMember
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MiddleName { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BirthYear { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Role;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditedAs { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Voice;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Uncredited;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Puppeteer;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CrewDivider))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Divider
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DividerType Type;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum DividerType
    {

        /// <remarks/>
        Episode,

        /// <remarks/>
        Group,

        /// <remarks/>
        EndDiv,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrewDivider : Divider
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditType;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AudioTrack
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AudioContent")]
        public string Content;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AudioFormat")]
        public string Format;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AudioChannels")]
        public string Channels;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Features
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureSceneAccess")]
        public bool SceneAccess;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureCommentary")]
        public bool Commentary;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureTrailer")]
        public bool Trailer;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeaturePhotoGallery")]
        public bool PhotoGallery;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureDeletedScenes")]
        public bool DeletedScenes;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureMakingOf")]
        public bool MakingOf;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureProductionNotes")]
        public bool ProductionNotes;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureGame")]
        public bool Game;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureDVDROMContent")]
        public bool DVDROMContent;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureMultiAngle")]
        public bool MultiAngle;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureMusicVideos")]
        public bool MusicVideos;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureInterviews")]
        public bool Interviews;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureStoryboardComparisons")]
        public bool StoryboardComparisons;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureOuttakes")]
        public bool Outtakes;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureClosedCaptioned")]
        public bool ClosedCaptioned;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureTHXCertified")]
        public bool THXCertified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeaturePIP")]
        public bool PIP;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureBDLive")]
        public bool BDLive;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureBonusTrailers")]
        public bool BonusTrailers;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureDigitalCopy")]
        public bool DigitalCopy;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureDBOX")]
        public bool DBOX;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureCineChat")]
        public bool CineChat;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeaturePlayAll")]
        public bool PlayAll;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureMovieIQ")]
        public bool MovieIQ;

        /// <remarks/>
        public string OtherFeatures;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Dimensions
    {

        /// <remarks/>
        public bool Dim2D;

        /// <remarks/>
        public bool Dim3DAnaglyph;

        /// <remarks/>
        public bool Dim3DBluRay;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatColor
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClrColor")]
        public bool Color;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClrBlackAndWhite")]
        public bool BlackAndWhite;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClrColorized")]
        public bool Colorized;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClrMixed")]
        public bool Mixed;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Format
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatAspectRatio")]
        public string AspectRatio;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatVideoStandard")]
        public VideoStandard VideoStandard;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ColorFormat")]
        public FormatColor Color;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatLetterBox")]
        public bool LetterBox;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatPanAndScan")]
        public bool PanAndScan;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatFullFrame")]
        public bool FullFrame;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Format16X9")]
        public bool Enhanced16X9;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatDualSided")]
        public bool DualSided;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatDualLayered")]
        public bool DualLayered;

        /// <remarks/>
        public Dimensions Dimensions;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum VideoStandard
    {

        /// <remarks/>
        NTSC,

        /// <remarks/>
        PAL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollectionType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPartOfOwnedCollection;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CastInformation
    {

        /// <remarks/>
        public string Title;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Actor", typeof(CastMember), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(Divider), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Actors")]
        public object[] CastList;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CrewInformation
    {

        /// <remarks/>
        public string Title;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Credit", typeof(CrewMember), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(CrewDivider), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Credits")]
        public object[] CrewList;
    }
}