////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.269
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//// 
//// This source code was auto-generated by xsd, Version=4.0.30319.1.
//// 
//namespace DoenaSoft.DVDProfiler.DVDProfilerXML.Version381
//{
//    using System.Xml.Serialization;


//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute("COOs", Namespace = "", IsNullable = false)]
//    public partial class CountryOfOriginList
//    {

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("COO", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//        public CountryOfOriginEntry[] COO;
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class CountryOfOriginEntry
//    {

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int ID;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Desc;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public bool Legacy;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool LegacySpecified;
//    }
//}