//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace DoenaSoft.DVDProfiler.DVDProfilerXML.Version381
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Collection
    {

        private DVD[] dVDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DVD")]
        public DVD[] DVDList
        {
            get
            {
                return this.dVDField;
            }
            set
            {
                this.dVDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DVD
    {

        private System.DateTime profileTimestampField;

        private string idField;

        private MediaTypes mediaTypesField;

        private string uPCField;

        private string collectionNumberField;

        private CollectionType collectionTypeField;

        private string titleField;

        private string distTraitField;

        private string originalTitleField;

        private string countryOfOriginField;

        private string countryOfOrigin2Field;

        private string countryOfOrigin3Field;

        private int productionYearField;

        private System.DateTime releasedField;

        private bool releasedFieldSpecified;

        private int runningTimeField;

        private string ratingSystemField;

        private string ratingField;

        private int ratingAgeField;

        private int ratingVariantField;

        private string ratingDetailsField;

        private string caseTypeField;

        private bool caseSlipCoverField;

        private bool caseSlipCoverFieldSpecified;

        private string[] genresField;

        private string[] regionsField;

        private Format formatField;

        private Features featuresField;

        private string[] studiosField;

        private string[] mediaCompaniesField;

        private AudioTrack[] audioField;

        private string[] subtitlesField;

        private Price sRPField;

        private object[] actorsField;

        private object[] creditsField;

        private string overviewField;

        private string easterEggsField;

        private Disc[] discsField;

        private string sortTitleField;

        private System.DateTime lastEditedField;

        private bool lastEditedFieldSpecified;

        private int wishPriorityField;

        private int countAsField;

        private PurchaseInfo purchaseInfoField;

        private Review reviewField;

        private MediaBanners mediaBannersField;

        private Exclusions exclusionsField;

        private Event[] eventsField;

        private BoxSet boxSetField;

        private LoanInfo loanInfoField;

        private MyLinks myLinksField;

        private string notesField;

        private Tag[] tagsField;

        private Locks locksField;

        /// <remarks/>
        public System.DateTime ProfileTimestamp
        {
            get
            {
                return this.profileTimestampField;
            }
            set
            {
                this.profileTimestampField = value;
            }
        }

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public MediaTypes MediaTypes
        {
            get
            {
                return this.mediaTypesField;
            }
            set
            {
                this.mediaTypesField = value;
            }
        }

        /// <remarks/>
        public string UPC
        {
            get
            {
                return this.uPCField;
            }
            set
            {
                this.uPCField = value;
            }
        }

        /// <remarks/>
        public string CollectionNumber
        {
            get
            {
                return this.collectionNumberField;
            }
            set
            {
                this.collectionNumberField = value;
            }
        }

        /// <remarks/>
        public CollectionType CollectionType
        {
            get
            {
                return this.collectionTypeField;
            }
            set
            {
                this.collectionTypeField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DistTrait")]
        public string Edition
        {
            get
            {
                return this.distTraitField;
            }
            set
            {
                this.distTraitField = value;
            }
        }

        /// <remarks/>
        public string OriginalTitle
        {
            get
            {
                return this.originalTitleField;
            }
            set
            {
                this.originalTitleField = value;
            }
        }

        /// <remarks/>
        public string CountryOfOrigin
        {
            get
            {
                return this.countryOfOriginField;
            }
            set
            {
                this.countryOfOriginField = value;
            }
        }

        /// <remarks/>
        public string CountryOfOrigin2
        {
            get
            {
                return this.countryOfOrigin2Field;
            }
            set
            {
                this.countryOfOrigin2Field = value;
            }
        }

        /// <remarks/>
        public string CountryOfOrigin3
        {
            get
            {
                return this.countryOfOrigin3Field;
            }
            set
            {
                this.countryOfOrigin3Field = value;
            }
        }

        /// <remarks/>
        public int ProductionYear
        {
            get
            {
                return this.productionYearField;
            }
            set
            {
                this.productionYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Released
        {
            get
            {
                return this.releasedField;
            }
            set
            {
                this.releasedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleasedSpecified
        {
            get
            {
                return this.releasedFieldSpecified;
            }
            set
            {
                this.releasedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int RunningTime
        {
            get
            {
                return this.runningTimeField;
            }
            set
            {
                this.runningTimeField = value;
            }
        }

        /// <remarks/>
        public string RatingSystem
        {
            get
            {
                return this.ratingSystemField;
            }
            set
            {
                this.ratingSystemField = value;
            }
        }

        /// <remarks/>
        public string Rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }

        /// <remarks/>
        public int RatingAge
        {
            get
            {
                return this.ratingAgeField;
            }
            set
            {
                this.ratingAgeField = value;
            }
        }

        /// <remarks/>
        public int RatingVariant
        {
            get
            {
                return this.ratingVariantField;
            }
            set
            {
                this.ratingVariantField = value;
            }
        }

        /// <remarks/>
        public string RatingDetails
        {
            get
            {
                return this.ratingDetailsField;
            }
            set
            {
                this.ratingDetailsField = value;
            }
        }

        /// <remarks/>
        public string CaseType
        {
            get
            {
                return this.caseTypeField;
            }
            set
            {
                this.caseTypeField = value;
            }
        }

        /// <remarks/>
        public bool CaseSlipCover
        {
            get
            {
                return this.caseSlipCoverField;
            }
            set
            {
                this.caseSlipCoverField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CaseSlipCoverSpecified
        {
            get
            {
                return this.caseSlipCoverFieldSpecified;
            }
            set
            {
                this.caseSlipCoverFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Genre", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Genres")]        
        public string[] GenreList
        {
            get
            {
                return this.genresField;
            }
            set
            {
                this.genresField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Region", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Regions")]
        public string[] RegionList
        {
            get
            {
                return this.regionsField;
            }
            set
            {
                this.regionsField = value;
            }
        }

        /// <remarks/>
        public Format Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public Features Features
        {
            get
            {
                return this.featuresField;
            }
            set
            {
                this.featuresField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Studio", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Studios")]
        public string[] StudioList
        {
            get
            {
                return this.studiosField;
            }
            set
            {
                this.studiosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MediaCompany", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("MediaCompanies")]
        public string[] MediaCompanyList
        {
            get
            {
                return this.mediaCompaniesField;
            }
            set
            {
                this.mediaCompaniesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AudioTrack", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Audio")]
        public AudioTrack[] AudioList
        {
            get
            {
                return this.audioField;
            }
            set
            {
                this.audioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Subtitle", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Subtitles")]
        public string[] SubtitleList
        {
            get
            {
                return this.subtitlesField;
            }
            set
            {
                this.subtitlesField = value;
            }
        }

        /// <remarks/>
        public Price SRP
        {
            get
            {
                return this.sRPField;
            }
            set
            {
                this.sRPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Actor", typeof(CastMember), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(Divider), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Actors")]
        public object[] CastList
        {
            get
            {
                return this.actorsField;
            }
            set
            {
                this.actorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Credit", typeof(CrewMember), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(CrewDivider), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Credits")]
        public object[] CrewList
        {
            get
            {
                return this.creditsField;
            }
            set
            {
                this.creditsField = value;
            }
        }

        /// <remarks/>
        public string Overview
        {
            get
            {
                return this.overviewField;
            }
            set
            {
                this.overviewField = value;
            }
        }

        /// <remarks/>
        public string EasterEggs
        {
            get
            {
                return this.easterEggsField;
            }
            set
            {
                this.easterEggsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Disc", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Discs")]
        public Disc[] DiscList
        {
            get
            {
                return this.discsField;
            }
            set
            {
                this.discsField = value;
            }
        }

        /// <remarks/>
        public string SortTitle
        {
            get
            {
                return this.sortTitleField;
            }
            set
            {
                this.sortTitleField = value;
            }
        }

        /// <remarks/>
        public System.DateTime LastEdited
        {
            get
            {
                return this.lastEditedField;
            }
            set
            {
                this.lastEditedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastEditedSpecified
        {
            get
            {
                return this.lastEditedFieldSpecified;
            }
            set
            {
                this.lastEditedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int WishPriority
        {
            get
            {
                return this.wishPriorityField;
            }
            set
            {
                this.wishPriorityField = value;
            }
        }

        /// <remarks/>
        public int CountAs
        {
            get
            {
                return this.countAsField;
            }
            set
            {
                this.countAsField = value;
            }
        }

        /// <remarks/>
        public PurchaseInfo PurchaseInfo
        {
            get
            {
                return this.purchaseInfoField;
            }
            set
            {
                this.purchaseInfoField = value;
            }
        }

        /// <remarks/>
        public Review Review
        {
            get
            {
                return this.reviewField;
            }
            set
            {
                this.reviewField = value;
            }
        }

        /// <remarks/>
        public MediaBanners MediaBanners
        {
            get
            {
                return this.mediaBannersField;
            }
            set
            {
                this.mediaBannersField = value;
            }
        }

        /// <remarks/>
        public Exclusions Exclusions
        {
            get
            {
                return this.exclusionsField;
            }
            set
            {
                this.exclusionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Event", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Events")]
        public Event[] EventList
        {
            get
            {
                return this.eventsField;
            }
            set
            {
                this.eventsField = value;
            }
        }

        /// <remarks/>
        public BoxSet BoxSet
        {
            get
            {
                return this.boxSetField;
            }
            set
            {
                this.boxSetField = value;
            }
        }

        /// <remarks/>
        public LoanInfo LoanInfo
        {
            get
            {
                return this.loanInfoField;
            }
            set
            {
                this.loanInfoField = value;
            }
        }

        /// <remarks/>
        public MyLinks MyLinks
        {
            get
            {
                return this.myLinksField;
            }
            set
            {
                this.myLinksField = value;
            }
        }

        /// <remarks/>
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Tags")]
        public Tag[] TagList
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }

        /// <remarks/>
        public Locks Locks
        {
            get
            {
                return this.locksField;
            }
            set
            {
                this.locksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MediaTypes
    {

        private bool dVDField;

        private bool hDDVDField;

        private bool bluRayField;

        private string customMediaTypeField;

        /// <remarks/>
        public bool DVD
        {
            get
            {
                return this.dVDField;
            }
            set
            {
                this.dVDField = value;
            }
        }

        /// <remarks/>
        public bool HDDVD
        {
            get
            {
                return this.hDDVDField;
            }
            set
            {
                this.hDDVDField = value;
            }
        }

        /// <remarks/>
        public bool BluRay
        {
            get
            {
                return this.bluRayField;
            }
            set
            {
                this.bluRayField = value;
            }
        }

        /// <remarks/>
        public string CustomMediaType
        {
            get
            {
                return this.customMediaTypeField;
            }
            set
            {
                this.customMediaTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BasicDVD
    {

        private string idField;

        private MediaTypes mediaTypesField;

        private string uPCField;

        private string collectionNumberField;

        private CollectionType collectionTypeField;

        private string titleField;

        private string distTraitField;

        private string originalTitleField;

        private string countryOfOriginField;

        private string countryOfOrigin2Field;

        private string countryOfOrigin3Field;

        private int productionYearField;

        private System.DateTime releasedField;

        private bool releasedFieldSpecified;

        private int runningTimeField;

        private string ratingSystemField;

        private string ratingField;

        private int ratingAgeField;

        private int ratingVariantField;

        private string caseTypeField;

        private bool caseSlipCoverField;

        private bool caseSlipCoverFieldSpecified;

        private string overviewField;

        private string easterEggsField;

        private string sortTitleField;

        private System.DateTime lastEditedField;

        private bool lastEditedFieldSpecified;

        private int wishPriorityField;

        private int countAsField;

        private string notesField;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public MediaTypes MediaTypes
        {
            get
            {
                return this.mediaTypesField;
            }
            set
            {
                this.mediaTypesField = value;
            }
        }

        /// <remarks/>
        public string UPC
        {
            get
            {
                return this.uPCField;
            }
            set
            {
                this.uPCField = value;
            }
        }

        /// <remarks/>
        public string CollectionNumber
        {
            get
            {
                return this.collectionNumberField;
            }
            set
            {
                this.collectionNumberField = value;
            }
        }

        /// <remarks/>
        public CollectionType CollectionType
        {
            get
            {
                return this.collectionTypeField;
            }
            set
            {
                this.collectionTypeField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DistTrait")]
        public string Edition
        {
            get
            {
                return this.distTraitField;
            }
            set
            {
                this.distTraitField = value;
            }
        }

        /// <remarks/>
        public string OriginalTitle
        {
            get
            {
                return this.originalTitleField;
            }
            set
            {
                this.originalTitleField = value;
            }
        }

        /// <remarks/>
        public string CountryOfOrigin
        {
            get
            {
                return this.countryOfOriginField;
            }
            set
            {
                this.countryOfOriginField = value;
            }
        }

        /// <remarks/>
        public string CountryOfOrigin2
        {
            get
            {
                return this.countryOfOrigin2Field;
            }
            set
            {
                this.countryOfOrigin2Field = value;
            }
        }

        /// <remarks/>
        public string CountryOfOrigin3
        {
            get
            {
                return this.countryOfOrigin3Field;
            }
            set
            {
                this.countryOfOrigin3Field = value;
            }
        }

        /// <remarks/>
        public int ProductionYear
        {
            get
            {
                return this.productionYearField;
            }
            set
            {
                this.productionYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Released
        {
            get
            {
                return this.releasedField;
            }
            set
            {
                this.releasedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleasedSpecified
        {
            get
            {
                return this.releasedFieldSpecified;
            }
            set
            {
                this.releasedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int RunningTime
        {
            get
            {
                return this.runningTimeField;
            }
            set
            {
                this.runningTimeField = value;
            }
        }

        /// <remarks/>
        public string RatingSystem
        {
            get
            {
                return this.ratingSystemField;
            }
            set
            {
                this.ratingSystemField = value;
            }
        }

        /// <remarks/>
        public string Rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }

        /// <remarks/>
        public int RatingAge
        {
            get
            {
                return this.ratingAgeField;
            }
            set
            {
                this.ratingAgeField = value;
            }
        }

        /// <remarks/>
        public int RatingVariant
        {
            get
            {
                return this.ratingVariantField;
            }
            set
            {
                this.ratingVariantField = value;
            }
        }

        /// <remarks/>
        public string CaseType
        {
            get
            {
                return this.caseTypeField;
            }
            set
            {
                this.caseTypeField = value;
            }
        }

        /// <remarks/>
        public bool CaseSlipCover
        {
            get
            {
                return this.caseSlipCoverField;
            }
            set
            {
                this.caseSlipCoverField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CaseSlipCoverSpecified
        {
            get
            {
                return this.caseSlipCoverFieldSpecified;
            }
            set
            {
                this.caseSlipCoverFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Overview
        {
            get
            {
                return this.overviewField;
            }
            set
            {
                this.overviewField = value;
            }
        }

        /// <remarks/>
        public string EasterEggs
        {
            get
            {
                return this.easterEggsField;
            }
            set
            {
                this.easterEggsField = value;
            }
        }

        /// <remarks/>
        public string SortTitle
        {
            get
            {
                return this.sortTitleField;
            }
            set
            {
                this.sortTitleField = value;
            }
        }

        /// <remarks/>
        public System.DateTime LastEdited
        {
            get
            {
                return this.lastEditedField;
            }
            set
            {
                this.lastEditedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastEditedSpecified
        {
            get
            {
                return this.lastEditedFieldSpecified;
            }
            set
            {
                this.lastEditedFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int WishPriority
        {
            get
            {
                return this.wishPriorityField;
            }
            set
            {
                this.wishPriorityField = value;
            }
        }

        /// <remarks/>
        public int CountAs
        {
            get
            {
                return this.countAsField;
            }
            set
            {
                this.countAsField = value;
            }
        }

        /// <remarks/>
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollectionType
    {

        private bool isPartOfOwnedCollectionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPartOfOwnedCollection
        {
            get
            {
                return this.isPartOfOwnedCollectionField;
            }
            set
            {
                this.isPartOfOwnedCollectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Locks
    {

        private bool entireField;

        private bool coversField;

        private bool titleField;

        private bool mediaTypeField;

        private bool overviewField;

        private bool regionsField;

        private bool genresField;

        private bool sRPField;

        private bool studiosField;

        private bool discInformationField;

        private bool castField;

        private bool crewField;

        private bool featuresField;

        private bool audioTracksField;

        private bool subtitlesField;

        private bool easterEggsField;

        private bool runningTimeField;

        private bool releaseDateField;

        private bool productionYearField;

        private bool caseTypeField;

        private bool videoFormatsField;

        private bool ratingField;

        /// <remarks/>
        public bool Entire
        {
            get
            {
                return this.entireField;
            }
            set
            {
                this.entireField = value;
            }
        }

        /// <remarks/>
        public bool Covers
        {
            get
            {
                return this.coversField;
            }
            set
            {
                this.coversField = value;
            }
        }

        /// <remarks/>
        public bool Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public bool MediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }

        /// <remarks/>
        public bool Overview
        {
            get
            {
                return this.overviewField;
            }
            set
            {
                this.overviewField = value;
            }
        }

        /// <remarks/>
        public bool Regions
        {
            get
            {
                return this.regionsField;
            }
            set
            {
                this.regionsField = value;
            }
        }

        /// <remarks/>
        public bool Genres
        {
            get
            {
                return this.genresField;
            }
            set
            {
                this.genresField = value;
            }
        }

        /// <remarks/>
        public bool SRP
        {
            get
            {
                return this.sRPField;
            }
            set
            {
                this.sRPField = value;
            }
        }

        /// <remarks/>
        public bool Studios
        {
            get
            {
                return this.studiosField;
            }
            set
            {
                this.studiosField = value;
            }
        }

        /// <remarks/>
        public bool DiscInformation
        {
            get
            {
                return this.discInformationField;
            }
            set
            {
                this.discInformationField = value;
            }
        }

        /// <remarks/>
        public bool Cast
        {
            get
            {
                return this.castField;
            }
            set
            {
                this.castField = value;
            }
        }

        /// <remarks/>
        public bool Crew
        {
            get
            {
                return this.crewField;
            }
            set
            {
                this.crewField = value;
            }
        }

        /// <remarks/>
        public bool Features
        {
            get
            {
                return this.featuresField;
            }
            set
            {
                this.featuresField = value;
            }
        }

        /// <remarks/>
        public bool AudioTracks
        {
            get
            {
                return this.audioTracksField;
            }
            set
            {
                this.audioTracksField = value;
            }
        }

        /// <remarks/>
        public bool Subtitles
        {
            get
            {
                return this.subtitlesField;
            }
            set
            {
                this.subtitlesField = value;
            }
        }

        /// <remarks/>
        public bool EasterEggs
        {
            get
            {
                return this.easterEggsField;
            }
            set
            {
                this.easterEggsField = value;
            }
        }

        /// <remarks/>
        public bool RunningTime
        {
            get
            {
                return this.runningTimeField;
            }
            set
            {
                this.runningTimeField = value;
            }
        }

        /// <remarks/>
        public bool ReleaseDate
        {
            get
            {
                return this.releaseDateField;
            }
            set
            {
                this.releaseDateField = value;
            }
        }

        /// <remarks/>
        public bool ProductionYear
        {
            get
            {
                return this.productionYearField;
            }
            set
            {
                this.productionYearField = value;
            }
        }

        /// <remarks/>
        public bool CaseType
        {
            get
            {
                return this.caseTypeField;
            }
            set
            {
                this.caseTypeField = value;
            }
        }

        /// <remarks/>
        public bool VideoFormats
        {
            get
            {
                return this.videoFormatsField;
            }
            set
            {
                this.videoFormatsField = value;
            }
        }

        /// <remarks/>
        public bool Rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Tag
    {

        private string nameField;

        private string fullNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserLink
    {

        private string uRLField;

        private string descriptionField;

        private CategoryRestriction categoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CategoryRestriction Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum CategoryRestriction
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Empty,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Official Websites")]
        OfficialWebsites,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Fan Sites")]
        FanSites,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Trailers and Clips")]
        TrailersAndClips,

        /// <remarks/>
        Reviews,

        /// <remarks/>
        Ratings,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Information")]
        GeneralInformation,

        /// <remarks/>
        Games,

        /// <remarks/>
        Other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MyLinks
    {

        private UserLink[] customLinksField;

        /// <remarks/>        
        [System.Xml.Serialization.XmlArrayItemAttribute("UserLink", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("CustomLinks")]
        public UserLink[] UserLinkList
        {
            get
            {
                return this.customLinksField;
            }
            set
            {
                this.customLinksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanInfo
    {

        private bool loanedField;

        private System.DateTime dueField;

        private bool dueFieldSpecified;

        private User userField;

        /// <remarks/>
        public bool Loaned
        {
            get
            {
                return this.loanedField;
            }
            set
            {
                this.loanedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Due
        {
            get
            {
                return this.dueField;
            }
            set
            {
                this.dueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DueSpecified
        {
            get
            {
                return this.dueFieldSpecified;
            }
            set
            {
                this.dueFieldSpecified = value;
            }
        }

        /// <remarks/>
        public User User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User : BasicUser
    {
        private string emailAddressField;

        private string phoneNumberField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BasicUser
    {

        private string firstNameField;

        private string lastNameField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoxSet
    {

        private string parentField;

        private string[] contentsField;

        /// <remarks/>
        public string Parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Content", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Contents")]
        public string[] ContentList
        {
            get
            {
                return this.contentsField;
            }
            set
            {
                this.contentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Event
    {

        private EventType eventTypeField;

        private System.DateTime timestampField;

        private string noteField;

        private User userField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EventType")]
        public EventType Type
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }

        /// <remarks/>
        public User User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum EventType
    {

        /// <remarks/>
        Watched,

        /// <remarks/>
        Returned,

        /// <remarks/>
        Borrowed,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Exclusions
    {

        private bool moviePickField;

        private bool moviePickFieldSpecified;

        private bool mobileField;

        private bool mobileFieldSpecified;

        private bool iPhoneField;

        private bool iPhoneFieldSpecified;

        private bool remoteConnectionsField;

        private bool remoteConnectionsFieldSpecified;

        private bool dPOPublicField;

        private bool dPOPublicFieldSpecified;

        private bool dPOPrivateField;

        private bool dPOPrivateFieldSpecified;

        /// <remarks/>
        public bool MoviePick
        {
            get
            {
                return this.moviePickField;
            }
            set
            {
                this.moviePickField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MoviePickSpecified
        {
            get
            {
                return this.moviePickFieldSpecified;
            }
            set
            {
                this.moviePickFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MobileSpecified
        {
            get
            {
                return this.mobileFieldSpecified;
            }
            set
            {
                this.mobileFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool iPhone
        {
            get
            {
                return this.iPhoneField;
            }
            set
            {
                this.iPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iPhoneSpecified
        {
            get
            {
                return this.iPhoneFieldSpecified;
            }
            set
            {
                this.iPhoneFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool RemoteConnections
        {
            get
            {
                return this.remoteConnectionsField;
            }
            set
            {
                this.remoteConnectionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemoteConnectionsSpecified
        {
            get
            {
                return this.remoteConnectionsFieldSpecified;
            }
            set
            {
                this.remoteConnectionsFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool DPOPublic
        {
            get
            {
                return this.dPOPublicField;
            }
            set
            {
                this.dPOPublicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DPOPublicSpecified
        {
            get
            {
                return this.dPOPublicFieldSpecified;
            }
            set
            {
                this.dPOPublicFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool DPOPrivate
        {
            get
            {
                return this.dPOPrivateField;
            }
            set
            {
                this.dPOPrivateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DPOPrivateSpecified
        {
            get
            {
                return this.dPOPrivateFieldSpecified;
            }
            set
            {
                this.dPOPrivateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MediaBanners
    {

        private MediaBannersRestriction frontField;

        private MediaBannersRestriction backField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MediaBannersRestriction Front
        {
            get
            {
                return this.frontField;
            }
            set
            {
                this.frontField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MediaBannersRestriction Back
        {
            get
            {
                return this.backField;
            }
            set
            {
                this.backField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum MediaBannersRestriction
    {

        /// <remarks/>
        On,

        /// <remarks/>
        Off,

        /// <remarks/>
        Automatic,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Review
    {

        private int filmField;

        private int videoField;

        private int audioField;

        private int extrasField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Film
        {
            get
            {
                return this.filmField;
            }
            set
            {
                this.filmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Video
        {
            get
            {
                return this.videoField;
            }
            set
            {
                this.videoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Audio
        {
            get
            {
                return this.audioField;
            }
            set
            {
                this.audioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Extras
        {
            get
            {
                return this.extrasField;
            }
            set
            {
                this.extrasField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PurchaseInfo
    {

        private Price purchasePriceField;

        private string purchasePlaceField;

        private string purchasePlaceTypeField;

        private string purchasePlaceWebsiteField;

        private System.DateTime purchaseDateField;

        private bool purchaseDateFieldSpecified;

        private bool receivedAsGiftField;

        private BasicUser giftFromField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchasePrice")]
        public Price Price
        {
            get
            {
                return this.purchasePriceField;
            }
            set
            {
                this.purchasePriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchasePlace")]
        public string Place
        {
            get
            {
                return this.purchasePlaceField;
            }
            set
            {
                this.purchasePlaceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("PurchasePlaceType")]
        public string Type
        {
            get
            {
                return this.purchasePlaceTypeField;
            }
            set
            {
                this.purchasePlaceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchasePlaceWebsite")]
        public string Website
        {
            get
            {
                return this.purchasePlaceWebsiteField;
            }
            set
            {
                this.purchasePlaceWebsiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseDate", DataType = "date")]
        public System.DateTime Date
        {
            get
            {
                return this.purchaseDateField;
            }
            set
            {
                this.purchaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified
        {
            get
            {
                return this.purchaseDateFieldSpecified;
            }
            set
            {
                this.purchaseDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool ReceivedAsGift
        {
            get
            {
                return this.receivedAsGiftField;
            }
            set
            {
                this.receivedAsGiftField = value;
            }
        }

        /// <remarks/>
        public BasicUser GiftFrom
        {
            get
            {
                return this.giftFromField;
            }
            set
            {
                this.giftFromField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Price
    {

        private string denominationTypeField;

        private string denominationDescField;

        private string formattedValueField;

        private float valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DenominationType
        {
            get
            {
                return this.denominationTypeField;
            }
            set
            {
                this.denominationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DenominationDesc
        {
            get
            {
                return this.denominationDescField;
            }
            set
            {
                this.denominationDescField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FormattedValue
        {
            get
            {
                return this.formattedValueField;
            }
            set
            {
                this.formattedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Disc
    {

        private string descriptionSideAField;

        private string descriptionSideBField;

        private string discIDSideAField;

        private string discIDSideBField;

        private string labelSideAField;

        private string labelSideBField;

        private bool dualLayeredSideAField;

        private bool dualLayeredSideBField;

        private bool dualSidedField;

        private string locationField;

        private string slotField;

        /// <remarks/>
        public string DescriptionSideA
        {
            get
            {
                return this.descriptionSideAField;
            }
            set
            {
                this.descriptionSideAField = value;
            }
        }

        /// <remarks/>
        public string DescriptionSideB
        {
            get
            {
                return this.descriptionSideBField;
            }
            set
            {
                this.descriptionSideBField = value;
            }
        }

        /// <remarks/>
        public string DiscIDSideA
        {
            get
            {
                return this.discIDSideAField;
            }
            set
            {
                this.discIDSideAField = value;
            }
        }

        /// <remarks/>
        public string DiscIDSideB
        {
            get
            {
                return this.discIDSideBField;
            }
            set
            {
                this.discIDSideBField = value;
            }
        }

        /// <remarks/>
        public string LabelSideA
        {
            get
            {
                return this.labelSideAField;
            }
            set
            {
                this.labelSideAField = value;
            }
        }

        /// <remarks/>
        public string LabelSideB
        {
            get
            {
                return this.labelSideBField;
            }
            set
            {
                this.labelSideBField = value;
            }
        }

        /// <remarks/>
        public bool DualLayeredSideA
        {
            get
            {
                return this.dualLayeredSideAField;
            }
            set
            {
                this.dualLayeredSideAField = value;
            }
        }

        /// <remarks/>
        public bool DualLayeredSideB
        {
            get
            {
                return this.dualLayeredSideBField;
            }
            set
            {
                this.dualLayeredSideBField = value;
            }
        }

        /// <remarks/>
        public bool DualSided
        {
            get
            {
                return this.dualSidedField;
            }
            set
            {
                this.dualSidedField = value;
            }
        }

        /// <remarks/>
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public string Slot
        {
            get
            {
                return this.slotField;
            }
            set
            {
                this.slotField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrewMember
    {

        private string firstNameField;

        private string middleNameField;

        private string lastNameField;

        private int birthYearField;

        private string creditTypeField;

        private string creditSubtypeField;

        private string creditedAsField;

        private string customRoleField;

        private bool customRoleFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BirthYear
        {
            get
            {
                return this.birthYearField;
            }
            set
            {
                this.birthYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditType
        {
            get
            {
                return this.creditTypeField;
            }
            set
            {
                this.creditTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditSubtype
        {
            get
            {
                return this.creditSubtypeField;
            }
            set
            {
                this.creditSubtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditedAs
        {
            get
            {
                return this.creditedAsField;
            }
            set
            {
                this.creditedAsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomRole
        {
            get
            {
                return this.customRoleField;
            }
            set
            {
                this.customRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomRoleSpecified
        {
            get
            {
                return this.customRoleFieldSpecified;
            }
            set
            {
                this.customRoleFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CastMember
    {

        private string firstNameField;

        private string middleNameField;

        private string lastNameField;

        private int birthYearField;

        private string roleField;

        private string creditedAsField;

        private bool voiceField;

        private bool uncreditedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int BirthYear
        {
            get
            {
                return this.birthYearField;
            }
            set
            {
                this.birthYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditedAs
        {
            get
            {
                return this.creditedAsField;
            }
            set
            {
                this.creditedAsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Voice
        {
            get
            {
                return this.voiceField;
            }
            set
            {
                this.voiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Uncredited
        {
            get
            {
                return this.uncreditedField;
            }
            set
            {
                this.uncreditedField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CrewDivider))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Divider
    {

        private string captionField;

        private DividerType typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption
        {
            get
            {
                return this.captionField;
            }
            set
            {
                this.captionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DividerType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum DividerType
    {

        /// <remarks/>
        Episode,

        /// <remarks/>
        Group,

        /// <remarks/>
        EndDiv,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrewDivider : Divider
    {

        private string creditTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreditType
        {
            get
            {
                return this.creditTypeField;
            }
            set
            {
                this.creditTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AudioTrack
    {

        private string audioContentField;

        private string audioFormatField;

        private string audioChannelsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AudioContent")]
        public string Content
        {
            get
            {
                return this.audioContentField;
            }
            set
            {
                this.audioContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AudioFormat")]
        public string Format
        {
            get
            {
                return this.audioFormatField;
            }
            set
            {
                this.audioFormatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AudioChannels")]
        public string Channels
        {
            get
            {
                return this.audioChannelsField;
            }
            set
            {
                this.audioChannelsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Features
    {

        private bool featureSceneAccessField;

        private bool featureCommentaryField;

        private bool featureTrailerField;

        private bool featurePhotoGalleryField;

        private bool featureDeletedScenesField;

        private bool featureMakingOfField;

        private bool featureProductionNotesField;

        private bool featureGameField;

        private bool featureDVDROMContentField;

        private bool featureMultiAngleField;

        private bool featureMusicVideosField;

        private bool featureInterviewsField;

        private bool featureStoryboardComparisonsField;

        private bool featureOuttakesField;

        private bool featureClosedCaptionedField;

        private bool featureTHXCertifiedField;

        private bool featurePIPField;

        private bool featureBDLiveField;

        private bool featureBonusTrailersField;

        private bool featureDigitalCopyField;

        private string otherFeaturesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureSceneAccess")]
        public bool SceneAccess
        {
            get
            {
                return this.featureSceneAccessField;
            }
            set
            {
                this.featureSceneAccessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureCommentary")]
        public bool Commentary
        {
            get
            {
                return this.featureCommentaryField;
            }
            set
            {
                this.featureCommentaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureTrailer")]
        public bool Trailer
        {
            get
            {
                return this.featureTrailerField;
            }
            set
            {
                this.featureTrailerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeaturePhotoGallery")]
        public bool PhotoGallery
        {
            get
            {
                return this.featurePhotoGalleryField;
            }
            set
            {
                this.featurePhotoGalleryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureDeletedScenes")]
        public bool DeletedScenes
        {
            get
            {
                return this.featureDeletedScenesField;
            }
            set
            {
                this.featureDeletedScenesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureMakingOf")]
        public bool MakingOf
        {
            get
            {
                return this.featureMakingOfField;
            }
            set
            {
                this.featureMakingOfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureProductionNotes")]
        public bool ProductionNotes
        {
            get
            {
                return this.featureProductionNotesField;
            }
            set
            {
                this.featureProductionNotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureGame")]
        public bool Game
        {
            get
            {
                return this.featureGameField;
            }
            set
            {
                this.featureGameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureDVDROMContent")]
        public bool DVDROMContent
        {
            get
            {
                return this.featureDVDROMContentField;
            }
            set
            {
                this.featureDVDROMContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureMultiAngle")]
        public bool MultiAngle
        {
            get
            {
                return this.featureMultiAngleField;
            }
            set
            {
                this.featureMultiAngleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureMusicVideos")]
        public bool MusicVideos
        {
            get
            {
                return this.featureMusicVideosField;
            }
            set
            {
                this.featureMusicVideosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureInterviews")]
        public bool Interviews
        {
            get
            {
                return this.featureInterviewsField;
            }
            set
            {
                this.featureInterviewsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureStoryboardComparisons")]
        public bool StoryboardComparisons
        {
            get
            {
                return this.featureStoryboardComparisonsField;
            }
            set
            {
                this.featureStoryboardComparisonsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureOuttakes")]
        public bool Outtakes
        {
            get
            {
                return this.featureOuttakesField;
            }
            set
            {
                this.featureOuttakesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureClosedCaptioned")]
        public bool ClosedCaptioned
        {
            get
            {
                return this.featureClosedCaptionedField;
            }
            set
            {
                this.featureClosedCaptionedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureTHXCertified")]
        public bool THXCertified
        {
            get
            {
                return this.featureTHXCertifiedField;
            }
            set
            {
                this.featureTHXCertifiedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeaturePIP")]
        public bool PIP
        {
            get
            {
                return this.featurePIPField;
            }
            set
            {
                this.featurePIPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureBDLive")]
        public bool BDLive
        {
            get
            {
                return this.featureBDLiveField;
            }
            set
            {
                this.featureBDLiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureBonusTrailers")]
        public bool BonusTrailers
        {
            get
            {
                return this.featureBonusTrailersField;
            }
            set
            {
                this.featureBonusTrailersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FeatureDigitalCopy")]
        public bool DigitalCopy
        {
            get
            {
                return this.featureDigitalCopyField;
            }
            set
            {
                this.featureDigitalCopyField = value;
            }
        }

        /// <remarks/>
        public string OtherFeatures
        {
            get
            {
                return this.otherFeaturesField;
            }
            set
            {
                this.otherFeaturesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Dimensions
    {

        private bool dim2DField;

        private bool dim3DAnaglyphField;

        private bool dim3DBluRayField;

        /// <remarks/>
        public bool Dim2D
        {
            get
            {
                return this.dim2DField;
            }
            set
            {
                this.dim2DField = value;
            }
        }

        /// <remarks/>
        public bool Dim3DAnaglyph
        {
            get
            {
                return this.dim3DAnaglyphField;
            }
            set
            {
                this.dim3DAnaglyphField = value;
            }
        }

        /// <remarks/>
        public bool Dim3DBluRay
        {
            get
            {
                return this.dim3DBluRayField;
            }
            set
            {
                this.dim3DBluRayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatColor
    {

        private bool clrColorField;

        private bool clrBlackAndWhiteField;

        private bool clrColorizedField;

        private bool clrMixedField;

        /// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ClrColor")]
        public bool Color
        {
            get
            {
                return this.clrColorField;
            }
            set
            {
                this.clrColorField = value;
            }
        }

        /// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ClrBlackAndWhite")]
        public bool BlackAndWhite
        {
            get
            {
                return this.clrBlackAndWhiteField;
            }
            set
            {
                this.clrBlackAndWhiteField = value;
            }
        }

        /// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ClrColorized")]
        public bool Colorized
        {
            get
            {
                return this.clrColorizedField;
            }
            set
            {
                this.clrColorizedField = value;
            }
        }

        /// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ClrMixed")]
        public bool Mixed
        {
            get
            {
                return this.clrMixedField;
            }
            set
            {
                this.clrMixedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Format
    {

        private string formatAspectRatioField;

        private VideoStandard formatVideoStandardField;

        private FormatColor formatColorField;

        private bool formatLetterBoxField;

        private bool formatPanAndScanField;

        private bool formatFullFrameField;

        private bool format16X9Field;

        private bool formatDualSidedField;

        private bool formatDualLayeredField;

        private Dimensions dimensionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatAspectRatio")]
        public string AspectRatio
        {
            get
            {
                return this.formatAspectRatioField;
            }
            set
            {
                this.formatAspectRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatVideoStandard")]
        public VideoStandard VideoStandard
        {
            get
            {
                return this.formatVideoStandardField;
            }
            set
            {
                this.formatVideoStandardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ColorFormat")]
        public FormatColor Color
        {
            get
            {
                return this.formatColorField;
            }
            set
            {
                this.formatColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatLetterBox")]
        public bool LetterBox
        {
            get
            {
                return this.formatLetterBoxField;
            }
            set
            {
                this.formatLetterBoxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatPanAndScan")]
        public bool PanAndScan
        {
            get
            {
                return this.formatPanAndScanField;
            }
            set
            {
                this.formatPanAndScanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatFullFrame")]
        public bool FullFrame
        {
            get
            {
                return this.formatFullFrameField;
            }
            set
            {
                this.formatFullFrameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Format16X9")]
        public bool Enhanced16X9
        {
            get
            {
                return this.format16X9Field;
            }
            set
            {
                this.format16X9Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatDualSided")]
        public bool DualSided
        {
            get
            {
                return this.formatDualSidedField;
            }
            set
            {
                this.formatDualSidedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormatDualLayered")]
        public bool DualLayered
        {
            get
            {
                return this.formatDualLayeredField;
            }
            set
            {
                this.formatDualLayeredField = value;
            }
        }

        /// <remarks/>
        public Dimensions Dimensions
        {
            get
            {
                return this.dimensionsField;
            }
            set
            {
                this.dimensionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum VideoStandard
    {

        /// <remarks/>
        NTSC,

        /// <remarks/>
        PAL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "Collection", Namespace = "", IsNullable = false)]
    public partial class BasicCollection
    {

        private BasicDVD[] dVDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DVD")]
        public BasicDVD[] DVDList
        {
            get
            {
                return this.dVDField;
            }
            set
            {
                this.dVDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CastInformation
    {

        private string titleField;

        private object[] actorsField;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Actor", typeof(CastMember), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(Divider), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Actors")]
        public object[] CastList
        {
            get
            {
                return this.actorsField;
            }
            set
            {
                this.actorsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CrewInformation
    {

        private string titleField;

        private object[] creditsField;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Credit", typeof(CrewMember), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(CrewDivider), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayAttribute("Credits")]
        public object[] CrewList
        {
            get
            {
                return this.creditsField;
            }
            set
            {
                this.creditsField = value;
            }
        }
    }
}