////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.269
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//// 
//// This source code was auto-generated by xsd, Version=4.0.30319.1.
//// 
//namespace DoenaSoft.DVDProfiler.DVDProfilerXML.Version381
//{
//    using System.Xml.Serialization;


//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
//    public partial class Localities
//    {

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("Locality", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//        public Locality[] LocalityList;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int LastUsedID;
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class Locality
//    {

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("Ratings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//        public Ratings[] RatingList;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Description;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int ID;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string DVDRegion;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string BDRegion;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string AmazonSiteName;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string AmazonSite;
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class Ratings
//    {

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("Rating", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//        public Rating[] RatingList;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Description;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int ID;
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class Rating
//    {

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int LegacyValue;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool LegacyValueSpecified;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Name;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Description;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int Age;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Variant;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Adult;
//    }
//}