////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.3603
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System;
//using System.Collections.Generic;
//using System.IO;
//using System.Text;
//using System.Xml;
//using System.Xml.Serialization;
//namespace DoenaSoft.DVDProfiler.DVDProfilerXML.Version351
//{
//    // 
//    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
//    // 


//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute("Collection", Namespace = "", IsNullable = false)]
//    public partial class CollectionType351
//    {
//        private static XmlSerializer s_XmlSerializer;

//        [XmlIgnore()]
//        public static XmlSerializer XmlSerializer
//        {
//            get
//            {
//                if (s_XmlSerializer == null)
//                {
//                    s_XmlSerializer = new XmlSerializer(typeof(CollectionType351));
//                }
//                return (s_XmlSerializer);
//            }
//        }

//        public static void Serialize(String fileName, CollectionType351 instance)
//        {
//            using (FileStream fs = new FileStream(fileName, FileMode.Create, FileAccess.Write, FileShare.None))
//            {
//                using (XmlTextWriter xtw = new XmlTextWriter(fs, Encoding.GetEncoding(1252)))
//                {
//                    xtw.Formatting = Formatting.Indented;
//                    XmlSerializer.Serialize(xtw, instance);
//                }
//            }
//        }

//        public void Serialize(String fileName)
//        {
//            Serialize(fileName, this);
//        }

//        public static CollectionType351 Deserialize(String fileName)
//        {
//            using (FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read))
//            {
//                using (XmlTextReader xtr = new XmlTextReader(fs))
//                {
//                    CollectionType351 instance;

//                    instance = (CollectionType351)(XmlSerializer.Deserialize(xtr));
//                    return (instance);
//                }
//            }
//        }

//        private DVDType[] dVDField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("DVD")]
//        public DVDType[] DVD
//        {
//            get
//            {
//                return this.dVDField;
//            }
//            set
//            {
//                this.dVDField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute("DVD", Namespace = "", IsNullable = false)]
//    public partial class DVDType
//    {
//        private static Dictionary<Int32, String> CountryDict;

//        private System.DateTime profileTimestampField;

//        private string idField;

//        private MediaTypesType mediaTypesField;

//        private string uPCField;

//        private string collectionNumberField;

//        private DVDTypeCollectionType collectionTypeField;

//        private string titleField;

//        private string distTraitField;

//        private string originalTitleField;

//        private string countryOfOriginField;

//        private int productionYearField;

//        private System.DateTime releasedField;

//        private bool releasedFieldSpecified;

//        private int runningTimeField;

//        private string ratingSystemField;

//        private string ratingField;

//        private int ratingAgeField;

//        private int ratingVariantField;

//        private string caseTypeField;

//        private bool caseSlipCoverField;

//        private bool caseSlipCoverFieldSpecified;

//        private string[] genresField;

//        private string[] regionsField;

//        private FormatType formatField;

//        private FeaturesType featuresField;

//        private string[] studiosField;

//        private string[] mediaCompaniesField;

//        private AudioTrackType[] audioField;

//        private string[] subtitlesField;

//        private PriceType sRPField;

//        private object[] actorsField;

//        private object[] creditsField;

//        private string overviewField;

//        private string easterEggsField;

//        private DiscType[] discsField;

//        private string sortTitleField;

//        private System.DateTime lastEditedField;

//        private bool lastEditedFieldSpecified;

//        private int wishPriorityField;

//        private PurchaseInfoType purchaseInfoField;

//        private ReviewType reviewField;

//        private EventType[] eventsField;

//        private BoxSetType boxSetField;

//        private LoanInfoType loanInfoField;

//        private string notesField;

//        private TagType[] tagsField;

//        private LocksType locksField;

//        static DVDType()
//        {
//            CountryDict = new Dictionary<Int32, String>();
//            CountryDict.Add(0, "United States");
//            CountryDict.Add(1, "New Zealand");
//            CountryDict.Add(2, "Australia");
//            CountryDict.Add(3, "Canada");
//            CountryDict.Add(4, "United Kingdom");
//            CountryDict.Add(5, "Germany");
//            CountryDict.Add(6, "China");
//            CountryDict.Add(7, "Former Soviet Union");
//            CountryDict.Add(8, "France");
//            CountryDict.Add(9, "Netherlands");
//            CountryDict.Add(10, "Spain");
//            CountryDict.Add(11, "Sweden");
//            CountryDict.Add(12, "Norway");
//            CountryDict.Add(13, "Italy");
//            CountryDict.Add(14, "Denmark");
//            CountryDict.Add(15, "Portugal");
//            CountryDict.Add(16, "Finland");
//            CountryDict.Add(17, "Japan");
//            CountryDict.Add(18, "Korea");
//            CountryDict.Add(19, "Canada (Quebec)");
//            CountryDict.Add(20, "South Africa");
//            CountryDict.Add(21, "Hong Kong");
//            CountryDict.Add(22, "Switzerland");
//            CountryDict.Add(23, "Brazil");
//            CountryDict.Add(24, "Israel");
//            CountryDict.Add(25, "Mexico");
//            CountryDict.Add(26, "Iceland");
//            CountryDict.Add(27, "Indonesia");
//            CountryDict.Add(28, "Taiwan");
//            CountryDict.Add(29, "Poland");
//            CountryDict.Add(30, "Belgium");
//            CountryDict.Add(31, "Turkey");
//            CountryDict.Add(32, "Argentina");
//            CountryDict.Add(33, "Slovakia");
//            CountryDict.Add(34, "Hungary");
//            CountryDict.Add(35, "Singapore");
//            CountryDict.Add(36, "Czech Republic");
//            CountryDict.Add(37, "Malaysia");
//            CountryDict.Add(38, "Thailand");
//            CountryDict.Add(39, "India");
//            CountryDict.Add(40, "Austria");
//            CountryDict.Add(41, "Greece");
//            CountryDict.Add(42, "Vietnam");
//        }

//        [XmlIgnore()]
//        public Int32 LocalityAsID
//        {
//            get
//            {
//                String[] split;

//                split = this.ID.Split('.');
//                if (split.Length == 1)
//                {
//                    return (0);
//                }
//                else
//                {
//                    return (Int32.Parse(split[1]));
//                }
//            }
//        }

//        [XmlIgnore()]
//        public String LocalityAsText
//        {
//            get
//            {
//                return (CountryDict[this.LocalityAsID]);
//            }
//        }

//        /// <remarks/>
//        public System.DateTime ProfileTimestamp
//        {
//            get
//            {
//                return this.profileTimestampField;
//            }
//            set
//            {
//                this.profileTimestampField = value;
//            }
//        }

//        /// <remarks/>
//        public string ID
//        {
//            get
//            {
//                return this.idField;
//            }
//            set
//            {
//                this.idField = value;
//            }
//        }

//        /// <remarks/>
//        public MediaTypesType MediaTypes
//        {
//            get
//            {
//                return this.mediaTypesField;
//            }
//            set
//            {
//                this.mediaTypesField = value;
//            }
//        }

//        /// <remarks/>
//        public string UPC
//        {
//            get
//            {
//                return this.uPCField;
//            }
//            set
//            {
//                this.uPCField = value;
//            }
//        }

//        /// <remarks/>
//        public string CollectionNumber
//        {
//            get
//            {
//                return this.collectionNumberField;
//            }
//            set
//            {
//                this.collectionNumberField = value;
//            }
//        }

//        /// <remarks/>
//        public DVDTypeCollectionType CollectionType
//        {
//            get
//            {
//                return this.collectionTypeField;
//            }
//            set
//            {
//                this.collectionTypeField = value;
//            }
//        }

//        /// <remarks/>
//        public string Title
//        {
//            get
//            {
//                return this.titleField;
//            }
//            set
//            {
//                this.titleField = value;
//            }
//        }

//        /// <remarks/>
//        public string DistTrait
//        {
//            get
//            {
//                return this.distTraitField;
//            }
//            set
//            {
//                this.distTraitField = value;
//            }
//        }

//        /// <remarks/>
//        public string OriginalTitle
//        {
//            get
//            {
//                return this.originalTitleField;
//            }
//            set
//            {
//                this.originalTitleField = value;
//            }
//        }

//        /// <remarks/>
//        public string CountryOfOrigin
//        {
//            get
//            {
//                return this.countryOfOriginField;
//            }
//            set
//            {
//                this.countryOfOriginField = value;
//            }
//        }

//        /// <remarks/>
//        public int ProductionYear
//        {
//            get
//            {
//                return this.productionYearField;
//            }
//            set
//            {
//                this.productionYearField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime Released
//        {
//            get
//            {
//                return this.releasedField;
//            }
//            set
//            {
//                this.releasedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool ReleasedSpecified
//        {
//            get
//            {
//                return this.releasedFieldSpecified;
//            }
//            set
//            {
//                this.releasedFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int RunningTime
//        {
//            get
//            {
//                return this.runningTimeField;
//            }
//            set
//            {
//                this.runningTimeField = value;
//            }
//        }

//        /// <remarks/>
//        public string RatingSystem
//        {
//            get
//            {
//                return this.ratingSystemField;
//            }
//            set
//            {
//                this.ratingSystemField = value;
//            }
//        }

//        /// <remarks/>
//        public string Rating
//        {
//            get
//            {
//                return this.ratingField;
//            }
//            set
//            {
//                this.ratingField = value;
//            }
//        }

//        /// <remarks/>
//        public int RatingAge
//        {
//            get
//            {
//                return this.ratingAgeField;
//            }
//            set
//            {
//                this.ratingAgeField = value;
//            }
//        }

//        /// <remarks/>
//        public int RatingVariant
//        {
//            get
//            {
//                return this.ratingVariantField;
//            }
//            set
//            {
//                this.ratingVariantField = value;
//            }
//        }

//        /// <remarks/>
//        public string CaseType
//        {
//            get
//            {
//                return this.caseTypeField;
//            }
//            set
//            {
//                this.caseTypeField = value;
//            }
//        }

//        /// <remarks/>
//        public bool CaseSlipCover
//        {
//            get
//            {
//                return this.caseSlipCoverField;
//            }
//            set
//            {
//                this.caseSlipCoverField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool CaseSlipCoverSpecified
//        {
//            get
//            {
//                return this.caseSlipCoverFieldSpecified;
//            }
//            set
//            {
//                this.caseSlipCoverFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Genre", IsNullable = false)]
//        public string[] Genres
//        {
//            get
//            {
//                return this.genresField;
//            }
//            set
//            {
//                this.genresField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Region", IsNullable = false)]
//        public string[] Regions
//        {
//            get
//            {
//                return this.regionsField;
//            }
//            set
//            {
//                this.regionsField = value;
//            }
//        }

//        /// <remarks/>
//        public FormatType Format
//        {
//            get
//            {
//                return this.formatField;
//            }
//            set
//            {
//                this.formatField = value;
//            }
//        }

//        /// <remarks/>
//        public FeaturesType Features
//        {
//            get
//            {
//                return this.featuresField;
//            }
//            set
//            {
//                this.featuresField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Studio", IsNullable = false)]
//        public string[] Studios
//        {
//            get
//            {
//                return this.studiosField;
//            }
//            set
//            {
//                this.studiosField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("MediaCompany", IsNullable = false)]
//        public string[] MediaCompanies
//        {
//            get
//            {
//                return this.mediaCompaniesField;
//            }
//            set
//            {
//                this.mediaCompaniesField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("AudioTrack", IsNullable = false)]
//        public AudioTrackType[] Audio
//        {
//            get
//            {
//                return this.audioField;
//            }
//            set
//            {
//                this.audioField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Subtitle", IsNullable = false)]
//        public string[] Subtitles
//        {
//            get
//            {
//                return this.subtitlesField;
//            }
//            set
//            {
//                this.subtitlesField = value;
//            }
//        }

//        /// <remarks/>
//        public PriceType SRP
//        {
//            get
//            {
//                return this.sRPField;
//            }
//            set
//            {
//                this.sRPField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Actor", typeof(ActorType), IsNullable = false)]
//        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(DividerType), IsNullable = false)]
//        public object[] Actors
//        {
//            get
//            {
//                return this.actorsField;
//            }
//            set
//            {
//                this.actorsField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Credit", typeof(CreditType), IsNullable = false)]
//        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(DividerType), IsNullable = false)]
//        public object[] Credits
//        {
//            get
//            {
//                return this.creditsField;
//            }
//            set
//            {
//                this.creditsField = value;
//            }
//        }

//        /// <remarks/>
//        public string Overview
//        {
//            get
//            {
//                return this.overviewField;
//            }
//            set
//            {
//                this.overviewField = value;
//            }
//        }

//        /// <remarks/>
//        public string EasterEggs
//        {
//            get
//            {
//                return this.easterEggsField;
//            }
//            set
//            {
//                this.easterEggsField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Disc", IsNullable = false)]
//        public DiscType[] Discs
//        {
//            get
//            {
//                return this.discsField;
//            }
//            set
//            {
//                this.discsField = value;
//            }
//        }

//        /// <remarks/>
//        public string SortTitle
//        {
//            get
//            {
//                return this.sortTitleField;
//            }
//            set
//            {
//                this.sortTitleField = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime LastEdited
//        {
//            get
//            {
//                return this.lastEditedField;
//            }
//            set
//            {
//                this.lastEditedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool LastEditedSpecified
//        {
//            get
//            {
//                return this.lastEditedFieldSpecified;
//            }
//            set
//            {
//                this.lastEditedFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public int WishPriority
//        {
//            get
//            {
//                return this.wishPriorityField;
//            }
//            set
//            {
//                this.wishPriorityField = value;
//            }
//        }

//        /// <remarks/>
//        public PurchaseInfoType PurchaseInfo
//        {
//            get
//            {
//                return this.purchaseInfoField;
//            }
//            set
//            {
//                this.purchaseInfoField = value;
//            }
//        }

//        /// <remarks/>
//        public ReviewType Review
//        {
//            get
//            {
//                return this.reviewField;
//            }
//            set
//            {
//                this.reviewField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Event", IsNullable = false)]
//        public EventType[] Events
//        {
//            get
//            {
//                return this.eventsField;
//            }
//            set
//            {
//                this.eventsField = value;
//            }
//        }

//        /// <remarks/>
//        public BoxSetType BoxSet
//        {
//            get
//            {
//                return this.boxSetField;
//            }
//            set
//            {
//                this.boxSetField = value;
//            }
//        }

//        /// <remarks/>
//        public LoanInfoType LoanInfo
//        {
//            get
//            {
//                return this.loanInfoField;
//            }
//            set
//            {
//                this.loanInfoField = value;
//            }
//        }

//        /// <remarks/>
//        public string Notes
//        {
//            get
//            {
//                return this.notesField;
//            }
//            set
//            {
//                this.notesField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable = false)]
//        public TagType[] Tags
//        {
//            get
//            {
//                return this.tagsField;
//            }
//            set
//            {
//                this.tagsField = value;
//            }
//        }

//        /// <remarks/>
//        public LocksType Locks
//        {
//            get
//            {
//                return this.locksField;
//            }
//            set
//            {
//                this.locksField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class MediaTypesType
//    {

//        private bool dVDField;

//        private bool hDDVDField;

//        private bool bluRayField;

//        /// <remarks/>
//        public bool DVD
//        {
//            get
//            {
//                return this.dVDField;
//            }
//            set
//            {
//                this.dVDField = value;
//            }
//        }

//        /// <remarks/>
//        public bool HDDVD
//        {
//            get
//            {
//                return this.hDDVDField;
//            }
//            set
//            {
//                this.hDDVDField = value;
//            }
//        }

//        /// <remarks/>
//        public bool BluRay
//        {
//            get
//            {
//                return this.bluRayField;
//            }
//            set
//            {
//                this.bluRayField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class LocksType
//    {

//        private bool entireField;

//        private bool coversField;

//        private bool titleField;

//        private bool mediaTypeField;

//        private bool overviewField;

//        private bool regionsField;

//        private bool genresField;

//        private bool sRPField;

//        private bool studiosField;

//        private bool discInformationField;

//        private bool castField;

//        private bool crewField;

//        private bool featuresField;

//        private bool audioTracksField;

//        private bool subtitlesField;

//        private bool easterEggsField;

//        private bool runningTimeField;

//        private bool releaseDateField;

//        private bool productionYearField;

//        private bool caseTypeField;

//        private bool videoFormatsField;

//        private bool ratingField;

//        /// <remarks/>
//        public bool Entire
//        {
//            get
//            {
//                return this.entireField;
//            }
//            set
//            {
//                this.entireField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Covers
//        {
//            get
//            {
//                return this.coversField;
//            }
//            set
//            {
//                this.coversField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Title
//        {
//            get
//            {
//                return this.titleField;
//            }
//            set
//            {
//                this.titleField = value;
//            }
//        }

//        /// <remarks/>
//        public bool MediaType
//        {
//            get
//            {
//                return this.mediaTypeField;
//            }
//            set
//            {
//                this.mediaTypeField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Overview
//        {
//            get
//            {
//                return this.overviewField;
//            }
//            set
//            {
//                this.overviewField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Regions
//        {
//            get
//            {
//                return this.regionsField;
//            }
//            set
//            {
//                this.regionsField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Genres
//        {
//            get
//            {
//                return this.genresField;
//            }
//            set
//            {
//                this.genresField = value;
//            }
//        }

//        /// <remarks/>
//        public bool SRP
//        {
//            get
//            {
//                return this.sRPField;
//            }
//            set
//            {
//                this.sRPField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Studios
//        {
//            get
//            {
//                return this.studiosField;
//            }
//            set
//            {
//                this.studiosField = value;
//            }
//        }

//        /// <remarks/>
//        public bool DiscInformation
//        {
//            get
//            {
//                return this.discInformationField;
//            }
//            set
//            {
//                this.discInformationField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Cast
//        {
//            get
//            {
//                return this.castField;
//            }
//            set
//            {
//                this.castField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Crew
//        {
//            get
//            {
//                return this.crewField;
//            }
//            set
//            {
//                this.crewField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Features
//        {
//            get
//            {
//                return this.featuresField;
//            }
//            set
//            {
//                this.featuresField = value;
//            }
//        }

//        /// <remarks/>
//        public bool AudioTracks
//        {
//            get
//            {
//                return this.audioTracksField;
//            }
//            set
//            {
//                this.audioTracksField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Subtitles
//        {
//            get
//            {
//                return this.subtitlesField;
//            }
//            set
//            {
//                this.subtitlesField = value;
//            }
//        }

//        /// <remarks/>
//        public bool EasterEggs
//        {
//            get
//            {
//                return this.easterEggsField;
//            }
//            set
//            {
//                this.easterEggsField = value;
//            }
//        }

//        /// <remarks/>
//        public bool RunningTime
//        {
//            get
//            {
//                return this.runningTimeField;
//            }
//            set
//            {
//                this.runningTimeField = value;
//            }
//        }

//        /// <remarks/>
//        public bool ReleaseDate
//        {
//            get
//            {
//                return this.releaseDateField;
//            }
//            set
//            {
//                this.releaseDateField = value;
//            }
//        }

//        /// <remarks/>
//        public bool ProductionYear
//        {
//            get
//            {
//                return this.productionYearField;
//            }
//            set
//            {
//                this.productionYearField = value;
//            }
//        }

//        /// <remarks/>
//        public bool CaseType
//        {
//            get
//            {
//                return this.caseTypeField;
//            }
//            set
//            {
//                this.caseTypeField = value;
//            }
//        }

//        /// <remarks/>
//        public bool VideoFormats
//        {
//            get
//            {
//                return this.videoFormatsField;
//            }
//            set
//            {
//                this.videoFormatsField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Rating
//        {
//            get
//            {
//                return this.ratingField;
//            }
//            set
//            {
//                this.ratingField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class TagType
//    {

//        private string nameField;

//        private string fullNameField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Name
//        {
//            get
//            {
//                return this.nameField;
//            }
//            set
//            {
//                this.nameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string FullName
//        {
//            get
//            {
//                return this.fullNameField;
//            }
//            set
//            {
//                this.fullNameField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class LoanInfoType
//    {

//        private bool loanedField;

//        private System.DateTime dueField;

//        private bool dueFieldSpecified;

//        private UserType userField;

//        /// <remarks/>
//        public bool Loaned
//        {
//            get
//            {
//                return this.loanedField;
//            }
//            set
//            {
//                this.loanedField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime Due
//        {
//            get
//            {
//                return this.dueField;
//            }
//            set
//            {
//                this.dueField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool DueSpecified
//        {
//            get
//            {
//                return this.dueFieldSpecified;
//            }
//            set
//            {
//                this.dueFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        public UserType User
//        {
//            get
//            {
//                return this.userField;
//            }
//            set
//            {
//                this.userField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class UserType
//    {

//        private string firstNameField;

//        private string lastNameField;

//        private string emailAddressField;

//        private string phoneNumberField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string FirstName
//        {
//            get
//            {
//                return this.firstNameField;
//            }
//            set
//            {
//                this.firstNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string LastName
//        {
//            get
//            {
//                return this.lastNameField;
//            }
//            set
//            {
//                this.lastNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string EmailAddress
//        {
//            get
//            {
//                return this.emailAddressField;
//            }
//            set
//            {
//                this.emailAddressField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string PhoneNumber
//        {
//            get
//            {
//                return this.phoneNumberField;
//            }
//            set
//            {
//                this.phoneNumberField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class BoxSetType
//    {

//        private string parentField;

//        private string[] contentsField;

//        /// <remarks/>
//        public string Parent
//        {
//            get
//            {
//                return this.parentField;
//            }
//            set
//            {
//                this.parentField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Content", IsNullable = false)]
//        public string[] Contents
//        {
//            get
//            {
//                return this.contentsField;
//            }
//            set
//            {
//                this.contentsField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class EventType
//    {

//        private EventTypeEventType eventType1Field;

//        private System.DateTime timestampField;

//        private UserType userField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("EventType")]
//        public EventTypeEventType EventType1
//        {
//            get
//            {
//                return this.eventType1Field;
//            }
//            set
//            {
//                this.eventType1Field = value;
//            }
//        }

//        /// <remarks/>
//        public System.DateTime Timestamp
//        {
//            get
//            {
//                return this.timestampField;
//            }
//            set
//            {
//                this.timestampField = value;
//            }
//        }

//        /// <remarks/>
//        public UserType User
//        {
//            get
//            {
//                return this.userField;
//            }
//            set
//            {
//                this.userField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//    public enum EventTypeEventType
//    {

//        /// <remarks/>
//        Watched,

//        /// <remarks/>
//        Returned,

//        /// <remarks/>
//        Borrowed,
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class ReviewType
//    {

//        private int filmField;

//        private int videoField;

//        private int audioField;

//        private int extrasField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int Film
//        {
//            get
//            {
//                return this.filmField;
//            }
//            set
//            {
//                this.filmField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int Video
//        {
//            get
//            {
//                return this.videoField;
//            }
//            set
//            {
//                this.videoField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int Audio
//        {
//            get
//            {
//                return this.audioField;
//            }
//            set
//            {
//                this.audioField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int Extras
//        {
//            get
//            {
//                return this.extrasField;
//            }
//            set
//            {
//                this.extrasField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class PurchaseInfoType
//    {

//        private PriceType purchasePriceField;

//        private string purchasePlaceField;

//        private string purchasePlaceTypeField;

//        private string purchasePlaceWebsiteField;

//        private System.DateTime purchaseDateField;

//        private bool purchaseDateFieldSpecified;

//        /// <remarks/>
//        public PriceType PurchasePrice
//        {
//            get
//            {
//                return this.purchasePriceField;
//            }
//            set
//            {
//                this.purchasePriceField = value;
//            }
//        }

//        /// <remarks/>
//        public string PurchasePlace
//        {
//            get
//            {
//                return this.purchasePlaceField;
//            }
//            set
//            {
//                this.purchasePlaceField = value;
//            }
//        }

//        /// <remarks/>
//        public string PurchasePlaceType
//        {
//            get
//            {
//                return this.purchasePlaceTypeField;
//            }
//            set
//            {
//                this.purchasePlaceTypeField = value;
//            }
//        }

//        /// <remarks/>
//        public string PurchasePlaceWebsite
//        {
//            get
//            {
//                return this.purchasePlaceWebsiteField;
//            }
//            set
//            {
//                this.purchasePlaceWebsiteField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
//        public System.DateTime PurchaseDate
//        {
//            get
//            {
//                return this.purchaseDateField;
//            }
//            set
//            {
//                this.purchaseDateField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool PurchaseDateSpecified
//        {
//            get
//            {
//                return this.purchaseDateFieldSpecified;
//            }
//            set
//            {
//                this.purchaseDateFieldSpecified = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class PriceType
//    {

//        private string denominationTypeField;

//        private string denominationDescField;

//        private string formattedValueField;

//        private float valueField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string DenominationType
//        {
//            get
//            {
//                return this.denominationTypeField;
//            }
//            set
//            {
//                this.denominationTypeField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string DenominationDesc
//        {
//            get
//            {
//                return this.denominationDescField;
//            }
//            set
//            {
//                this.denominationDescField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string FormattedValue
//        {
//            get
//            {
//                return this.formattedValueField;
//            }
//            set
//            {
//                this.formattedValueField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlTextAttribute()]
//        public float Value
//        {
//            get
//            {
//                return this.valueField;
//            }
//            set
//            {
//                this.valueField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class DiscType
//    {

//        private string descriptionSideAField;

//        private string descriptionSideBField;

//        private string discIDSideAField;

//        private string discIDSideBField;

//        private string labelSideAField;

//        private string labelSideBField;

//        private bool dualLayeredSideAField;

//        private bool dualLayeredSideBField;

//        private bool dualSidedField;

//        private string locationField;

//        private string slotField;

//        /// <remarks/>
//        public string DescriptionSideA
//        {
//            get
//            {
//                return this.descriptionSideAField;
//            }
//            set
//            {
//                this.descriptionSideAField = value;
//            }
//        }

//        /// <remarks/>
//        public string DescriptionSideB
//        {
//            get
//            {
//                return this.descriptionSideBField;
//            }
//            set
//            {
//                this.descriptionSideBField = value;
//            }
//        }

//        /// <remarks/>
//        public string DiscIDSideA
//        {
//            get
//            {
//                return this.discIDSideAField;
//            }
//            set
//            {
//                this.discIDSideAField = value;
//            }
//        }

//        /// <remarks/>
//        public string DiscIDSideB
//        {
//            get
//            {
//                return this.discIDSideBField;
//            }
//            set
//            {
//                this.discIDSideBField = value;
//            }
//        }

//        /// <remarks/>
//        public string LabelSideA
//        {
//            get
//            {
//                return this.labelSideAField;
//            }
//            set
//            {
//                this.labelSideAField = value;
//            }
//        }

//        /// <remarks/>
//        public string LabelSideB
//        {
//            get
//            {
//                return this.labelSideBField;
//            }
//            set
//            {
//                this.labelSideBField = value;
//            }
//        }

//        /// <remarks/>
//        public bool DualLayeredSideA
//        {
//            get
//            {
//                return this.dualLayeredSideAField;
//            }
//            set
//            {
//                this.dualLayeredSideAField = value;
//            }
//        }

//        /// <remarks/>
//        public bool DualLayeredSideB
//        {
//            get
//            {
//                return this.dualLayeredSideBField;
//            }
//            set
//            {
//                this.dualLayeredSideBField = value;
//            }
//        }

//        /// <remarks/>
//        public bool DualSided
//        {
//            get
//            {
//                return this.dualSidedField;
//            }
//            set
//            {
//                this.dualSidedField = value;
//            }
//        }

//        /// <remarks/>
//        public string Location
//        {
//            get
//            {
//                return this.locationField;
//            }
//            set
//            {
//                this.locationField = value;
//            }
//        }

//        /// <remarks/>
//        public string Slot
//        {
//            get
//            {
//                return this.slotField;
//            }
//            set
//            {
//                this.slotField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class CreditType : IPerson
//    {

//        private string firstNameField;

//        private string middleNameField;

//        private string lastNameField;

//        private int birthYearField;

//        private string creditType1Field;

//        private string creditSubtypeField;

//        private string creditedAsField;

//        private string customRoleField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string FirstName
//        {
//            get
//            {
//                return this.firstNameField;
//            }
//            set
//            {
//                this.firstNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string MiddleName
//        {
//            get
//            {
//                return this.middleNameField;
//            }
//            set
//            {
//                this.middleNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string LastName
//        {
//            get
//            {
//                return this.lastNameField;
//            }
//            set
//            {
//                this.lastNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int BirthYear
//        {
//            get
//            {
//                return this.birthYearField;
//            }
//            set
//            {
//                this.birthYearField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute("CreditType")]
//        public string CreditType1
//        {
//            get
//            {
//                return this.creditType1Field;
//            }
//            set
//            {
//                this.creditType1Field = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string CreditSubtype
//        {
//            get
//            {
//                return this.creditSubtypeField;
//            }
//            set
//            {
//                this.creditSubtypeField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string CreditedAs
//        {
//            get
//            {
//                return this.creditedAsField;
//            }
//            set
//            {
//                this.creditedAsField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string CustomRole
//        {
//            get
//            {
//                return this.customRoleField;
//            }
//            set
//            {
//                this.customRoleField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class ActorType : IPerson
//    {

//        private string firstNameField;

//        private string middleNameField;

//        private string lastNameField;

//        private int birthYearField;

//        private string roleField;

//        private string creditedAsField;

//        private string voiceField;

//        private string uncreditedField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string FirstName
//        {
//            get
//            {
//                return this.firstNameField;
//            }
//            set
//            {
//                this.firstNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string MiddleName
//        {
//            get
//            {
//                return this.middleNameField;
//            }
//            set
//            {
//                this.middleNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string LastName
//        {
//            get
//            {
//                return this.lastNameField;
//            }
//            set
//            {
//                this.lastNameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int BirthYear
//        {
//            get
//            {
//                return this.birthYearField;
//            }
//            set
//            {
//                this.birthYearField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Role
//        {
//            get
//            {
//                return this.roleField;
//            }
//            set
//            {
//                this.roleField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string CreditedAs
//        {
//            get
//            {
//                return this.creditedAsField;
//            }
//            set
//            {
//                this.creditedAsField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Voice
//        {
//            get
//            {
//                return this.voiceField;
//            }
//            set
//            {
//                this.voiceField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Uncredited
//        {
//            get
//            {
//                return this.uncreditedField;
//            }
//            set
//            {
//                this.uncreditedField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class DividerType
//    {

//        private string captionField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Caption
//        {
//            get
//            {
//                return this.captionField;
//            }
//            set
//            {
//                this.captionField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class AudioTrackType
//    {

//        private string audioContentField;

//        private string audioFormatField;

//        /// <remarks/>
//        public string AudioContent
//        {
//            get
//            {
//                return this.audioContentField;
//            }
//            set
//            {
//                this.audioContentField = value;
//            }
//        }

//        /// <remarks/>
//        public string AudioFormat
//        {
//            get
//            {
//                return this.audioFormatField;
//            }
//            set
//            {
//                this.audioFormatField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class FeaturesType
//    {

//        private bool featureSceneAccessField;

//        private bool featureCommentaryField;

//        private bool featureTrailerField;

//        private bool featurePhotoGalleryField;

//        private bool featureDeletedScenesField;

//        private bool featureMakingOfField;

//        private bool featureProductionNotesField;

//        private bool featureGameField;

//        private bool featureDVDROMContentField;

//        private bool featureMultiAngleField;

//        private bool featureMusicVideosField;

//        private bool featureInterviewsField;

//        private bool featureStoryboardComparisonsField;

//        private bool featureOuttakesField;

//        private bool featureClosedCaptionedField;

//        private bool featureTHXCertifiedField;

//        private string otherFeaturesField;

//        /// <remarks/>
//        public bool FeatureSceneAccess
//        {
//            get
//            {
//                return this.featureSceneAccessField;
//            }
//            set
//            {
//                this.featureSceneAccessField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureCommentary
//        {
//            get
//            {
//                return this.featureCommentaryField;
//            }
//            set
//            {
//                this.featureCommentaryField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureTrailer
//        {
//            get
//            {
//                return this.featureTrailerField;
//            }
//            set
//            {
//                this.featureTrailerField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeaturePhotoGallery
//        {
//            get
//            {
//                return this.featurePhotoGalleryField;
//            }
//            set
//            {
//                this.featurePhotoGalleryField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureDeletedScenes
//        {
//            get
//            {
//                return this.featureDeletedScenesField;
//            }
//            set
//            {
//                this.featureDeletedScenesField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureMakingOf
//        {
//            get
//            {
//                return this.featureMakingOfField;
//            }
//            set
//            {
//                this.featureMakingOfField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureProductionNotes
//        {
//            get
//            {
//                return this.featureProductionNotesField;
//            }
//            set
//            {
//                this.featureProductionNotesField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureGame
//        {
//            get
//            {
//                return this.featureGameField;
//            }
//            set
//            {
//                this.featureGameField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureDVDROMContent
//        {
//            get
//            {
//                return this.featureDVDROMContentField;
//            }
//            set
//            {
//                this.featureDVDROMContentField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureMultiAngle
//        {
//            get
//            {
//                return this.featureMultiAngleField;
//            }
//            set
//            {
//                this.featureMultiAngleField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureMusicVideos
//        {
//            get
//            {
//                return this.featureMusicVideosField;
//            }
//            set
//            {
//                this.featureMusicVideosField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureInterviews
//        {
//            get
//            {
//                return this.featureInterviewsField;
//            }
//            set
//            {
//                this.featureInterviewsField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureStoryboardComparisons
//        {
//            get
//            {
//                return this.featureStoryboardComparisonsField;
//            }
//            set
//            {
//                this.featureStoryboardComparisonsField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureOuttakes
//        {
//            get
//            {
//                return this.featureOuttakesField;
//            }
//            set
//            {
//                this.featureOuttakesField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureClosedCaptioned
//        {
//            get
//            {
//                return this.featureClosedCaptionedField;
//            }
//            set
//            {
//                this.featureClosedCaptionedField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FeatureTHXCertified
//        {
//            get
//            {
//                return this.featureTHXCertifiedField;
//            }
//            set
//            {
//                this.featureTHXCertifiedField = value;
//            }
//        }

//        /// <remarks/>
//        public string OtherFeatures
//        {
//            get
//            {
//                return this.otherFeaturesField;
//            }
//            set
//            {
//                this.otherFeaturesField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class FormatType
//    {

//        private string formatAspectRatioField;

//        private FormatTypeFormatVideoStandard formatVideoStandardField;

//        private bool formatLetterBoxField;

//        private bool formatPanAndScanField;

//        private bool formatFullFrameField;

//        private bool format16X9Field;

//        private bool formatDualSidedField;

//        private bool formatDualLayeredField;

//        /// <remarks/>
//        public string FormatAspectRatio
//        {
//            get
//            {
//                return this.formatAspectRatioField;
//            }
//            set
//            {
//                this.formatAspectRatioField = value;
//            }
//        }

//        /// <remarks/>
//        public FormatTypeFormatVideoStandard FormatVideoStandard
//        {
//            get
//            {
//                return this.formatVideoStandardField;
//            }
//            set
//            {
//                this.formatVideoStandardField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FormatLetterBox
//        {
//            get
//            {
//                return this.formatLetterBoxField;
//            }
//            set
//            {
//                this.formatLetterBoxField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FormatPanAndScan
//        {
//            get
//            {
//                return this.formatPanAndScanField;
//            }
//            set
//            {
//                this.formatPanAndScanField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FormatFullFrame
//        {
//            get
//            {
//                return this.formatFullFrameField;
//            }
//            set
//            {
//                this.formatFullFrameField = value;
//            }
//        }

//        /// <remarks/>
//        public bool Format16X9
//        {
//            get
//            {
//                return this.format16X9Field;
//            }
//            set
//            {
//                this.format16X9Field = value;
//            }
//        }

//        /// <remarks/>
//        public bool FormatDualSided
//        {
//            get
//            {
//                return this.formatDualSidedField;
//            }
//            set
//            {
//                this.formatDualSidedField = value;
//            }
//        }

//        /// <remarks/>
//        public bool FormatDualLayered
//        {
//            get
//            {
//                return this.formatDualLayeredField;
//            }
//            set
//            {
//                this.formatDualLayeredField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//    public enum FormatTypeFormatVideoStandard
//    {

//        /// <remarks/>
//        NTSC,

//        /// <remarks/>
//        PAL,
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//    public enum DVDTypeCollectionType
//    {

//        /// <remarks/>
//        Owned,

//        /// <remarks/>
//        Ordered,

//        /// <remarks/>
//        [System.Xml.Serialization.XmlEnumAttribute("Wish List")]
//        WishList,
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute("CastInformation", Namespace = "", IsNullable = false)]
//    public partial class CastInformationType
//    {

//        private string titleField;

//        private object[] actorsField;

//        /// <remarks/>
//        public string Title
//        {
//            get
//            {
//                return this.titleField;
//            }
//            set
//            {
//                this.titleField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Actor", typeof(ActorType), IsNullable = false)]
//        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(DividerType), IsNullable = false)]
//        public object[] Actors
//        {
//            get
//            {
//                return this.actorsField;
//            }
//            set
//            {
//                this.actorsField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute("CrewInformation", Namespace = "", IsNullable = false)]
//    public partial class CrewInformationType
//    {

//        private string titleField;

//        private object[] creditsField;

//        /// <remarks/>
//        public string Title
//        {
//            get
//            {
//                return this.titleField;
//            }
//            set
//            {
//                this.titleField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute("Credit", typeof(CreditType), IsNullable = false)]
//        [System.Xml.Serialization.XmlArrayItemAttribute("Divider", typeof(DividerType), IsNullable = false)]
//        public object[] Credits
//        {
//            get
//            {
//                return this.creditsField;
//            }
//            set
//            {
//                this.creditsField = value;
//            }
//        }
//    }
//}