////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.3603
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;
//using System.Text;
//using System;
//using System.IO;
//using System.Xml;

//// 
//// This source code was auto-generated by xsd, Version=2.0.50727.3038.
//// 
//namespace DoenaSoft.DVDProfiler.DVDProfilerXML.Version360
//{

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
//    public partial class Localities
//    {
//        private static XmlSerializer s_XmlSerializer;

//        [XmlIgnore()]
//        public static XmlSerializer XmlSerializer
//        {
//            get
//            {
//                if(s_XmlSerializer == null)
//                {
//                    s_XmlSerializer = new XmlSerializer(typeof(Localities));
//                }
//                return (s_XmlSerializer);
//            }
//        }

//        public static Localities Deserialize(String fileName)
//        {
//            using(FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read))
//            {
//                using(XmlTextReader xtr = new XmlTextReader(fs))
//                {
//                    Localities instance;

//                    instance = (Localities)(XmlSerializer.Deserialize(xtr));
//                    return (instance);
//                }
//            }
//        }

//        public static Localities Deserialize()
//        {
//            String fileName;

//            fileName = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)
//                + @"\DVD Profiler\localities.xod";
//            if(File.Exists(fileName))
//            {
//                return (Deserialize(fileName));
//            }
//            else
//            {
//                return (null);
//            }
//        }

//        public override String ToString()
//        {
//            StringBuilder sb;

//            sb = new StringBuilder();
//            sb.Append("Count: ");
//            if(LocalityList != null)
//            {
//                sb.Append(LocalityList.Length);
//            }
//            else
//            {
//                sb.Append("none");
//            }
//            return (sb.ToString());
//        }

//        private Locality[] localityField;

//        private int lastUsedIDField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("Locality", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//        public Locality[] LocalityList
//        {
//            get
//            {
//                return localityField;
//            }
//            set
//            {
//                localityField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int LastUsedID
//        {
//            get
//            {
//                return lastUsedIDField;
//            }
//            set
//            {
//                lastUsedIDField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class Locality
//    {

//        private Ratings[] ratingsField;

//        private string descriptionField;

//        private int idField;

//        private string dVDRegionField;

//        private string bDRegionField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("Ratings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//        public Ratings[] RatingList
//        {
//            get
//            {
//                return ratingsField;
//            }
//            set
//            {
//                ratingsField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Description
//        {
//            get
//            {
//                return descriptionField;
//            }
//            set
//            {
//                descriptionField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int ID
//        {
//            get
//            {
//                return idField;
//            }
//            set
//            {
//                idField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string DVDRegion
//        {
//            get
//            {
//                return dVDRegionField;
//            }
//            set
//            {
//                dVDRegionField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string BDRegion
//        {
//            get
//            {
//                return bDRegionField;
//            }
//            set
//            {
//                bDRegionField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class Ratings
//    {

//        private Rating[] ratingField;

//        private string descriptionField;

//        private int idField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("Rating", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
//        public Rating[] RatingList
//        {
//            get
//            {
//                return ratingField;
//            }
//            set
//            {
//                ratingField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Description
//        {
//            get
//            {
//                return descriptionField;
//            }
//            set
//            {
//                descriptionField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int ID
//        {
//            get
//            {
//                return idField;
//            }
//            set
//            {
//                idField = value;
//            }
//        }
//    }

//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    public partial class Rating
//    {

//        private int legacyValueField;

//        private bool legacyValueFieldSpecified;

//        private string nameField;

//        private string descriptionField;

//        private int ageField;

//        private string variantField;

//        private string adultField;

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int LegacyValue
//        {
//            get
//            {
//                return legacyValueField;
//            }
//            set
//            {
//                legacyValueField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlIgnoreAttribute()]
//        public bool LegacyValueSpecified
//        {
//            get
//            {
//                return legacyValueFieldSpecified;
//            }
//            set
//            {
//                legacyValueFieldSpecified = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Name
//        {
//            get
//            {
//                return nameField;
//            }
//            set
//            {
//                nameField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Description
//        {
//            get
//            {
//                return descriptionField;
//            }
//            set
//            {
//                descriptionField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public int Age
//        {
//            get
//            {
//                return ageField;
//            }
//            set
//            {
//                ageField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Variant
//        {
//            get
//            {
//                return variantField;
//            }
//            set
//            {
//                variantField = value;
//            }
//        }

//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string Adult
//        {
//            get
//            {
//                return adultField;
//            }
//            set
//            {
//                adultField = value;
//            }
//        }
//    }
//}